/**
 * Contains classes used for parsing scene data from JSON files.
 * Automatically generated by Quicktype.
 * 
 * @see <a href="https://app.quicktype.io/">Quicktype</a>
 */
package io.quicktype.scenedata;
